version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bigdata_pg
    restart: always
    environment:
      POSTGRES_DB: bigdata
      POSTGRES_USER: bigdata_user
      POSTGRES_PASSWORD: bigdata_pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bigdata_user -d bigdata"]
      interval: 5s
      retries: 5
      timeout: 5s
